docs, modification

diff --git a/mshar b/mshar
--- a/mshar
+++ b/mshar
@@ -64,6 +64,13 @@ mkmshar(){
 		echo "MShar mkmshar: No archive name given";
 		return 1;
 	fi;
+
+	# check if base64 command is available
+	if ! command -v base64 >/dev/null 2>&1; then
+		echo "Error: base64 command not found, it is required to build the archive you loser.";
+		exit 1;
+	fi
+
 	# first part
 	{
 		echo "#!/bin/sh"; # make it executable with a shebang
@@ -117,85 +124,79 @@ mkmshar(){
 }
 
 # set operation
-OP="$1";
-shift;
 
-if ! test "$OP" = "noop"; then
+# check if no-op mode is active, use the MSHAR_NOOP variable
+if test -z "$MSHAR_NOOP"; then
+
 	# Hello
 	echo "MShar: MXPSQL's version of the Shell archiver";
-fi
 
-# check if $AR is defined
-if test -z "$OP"; then
-	echo "Usage: $(basename "$0") <mode>";
-	echo "		<mode> is one of the following:";
-	echo "			make-archive";
-	echo "			update-self";
-	echo "			noop";
-	echo "";
-	echo "		make-archive mode:";
-	echo "			create your archive";
-	echo "			args after the mode argument: <archive> [<file> ...]";
-	echo "				<archive> is the name of the archive";
-	echo "				<file> is the name of the file to add to the archive, add as much as you want";
-	echo "		update-self mode:";
-	echo "			updates the script itself";
-	echo "			args after the mode argument: none";
-	echo "		noop mode:";
-	echo "			does nothing, useful if you want to source the script";
-	echo "			args after the mode argument: none";
-	exit 1;
-fi
+	OP="$1";
 
-if test "$OP" = "make-archive"; then
-	# check if base64 command is available
-	if ! command -v base64 >/dev/null 2>&1; then
-		echo "Error: base64 command not found, it is required to build the archive you loser.";
+	# check if $OP is defined
+	if test -z "$OP"; then
+		echo "Usage: $(basename "$0") <mode>";
+		echo "		<mode> is one of the following:";
+		echo "			make-archive";
+		echo "			update-self";
+		echo "";
+		echo "		make-archive mode:";
+		echo "			create your archive";
+		echo "			args after the mode argument: <archive> [<file> ...]";
+		echo "				<archive> is the name of the archive";
+		echo "				<file> is the name of the file to add to the archive, add as much as you want";
+		echo "		update-self mode:";
+		echo "			updates the script itself";
+		echo "			args after the mode argument: none";
+		echo "";
+		echo "To noop, export or define the variable MSHAR_NOOP";
 		exit 1;
 	fi
 
-	# get the name of the archive
-	AR="$1";
 	shift;
 
-	# check if $AR is defined
-	if test -z "$AR"; then
-		echo "Usage: $(basename "$0") $OP <archive> [<file> ...]";
+	if test "$OP" = "make-archive"; then
+
+		# get the name of the archive
+		AR="$1";
+		shift;
+
+		# check if $AR is defined
+		if test -z "$AR"; then
+			echo "Usage: $(basename "$0") $OP <archive> [<file> ...]";
+		else
+			mkmshar "$AR" "$@";
+		fi
+
+		echo "Archive created. Archiving job done.";
+	elif test "$OP" = "update-self"; then
+		echo "Updating self";
+
+		if command -v git >/dev/null 2>&1 && test -d .git; then
+			echo "Using git to update self.";
+			git pull origin master;
+		elif command -v wget >/dev/null 2>&1; then
+			echo "Using wget to update self.";
+			wget -O "$0" "$RAW_URL";
+		elif command curl >/dev/null 2>&1; then
+			echo "Using curl to update self.";
+			curl -o "$0" "$RAW_URL";
+		else
+			echo "Error: git not found or the installation directory is not a git directory, you need git to update the script.";
+			echo "To update, please download the script from $REPO_URL and run it or get from $RAW_URL and download it.";
+		fi
+
+		echo "Done updating self.";
 	else
-		mkmshar "$AR" "$@";
+		echo "Invalid operation.";
 	fi
 
-	echo "Archive created. Archiving job done.";
-elif test "$OP" = "update-self"; then
-	echo "Updating self";
-
-	if command -v git >/dev/null 2>&1 && test -d .git; then
-		echo "Using git to update self.";
-		git pull origin master;
-	elif command -v wget >/dev/null 2>&1; then
-		echo "Using wget to update self.";
-		wget -O "$0" "$RAW_URL";
-	elif command curl >/dev/null 2>&1; then
-		echo "Using curl to update self.";
-		curl -o "$0" "$RAW_URL";
-	else
-		echo "Error: git not found or the installation directory is not a git directory, you need git to update the script.";
-		echo "To update, please download the script from $REPO_URL and run it or get from $RAW_URL and download it.";
-	fi
-
-	echo "Done updating self.";
-elif test "$OP" = "noop"; then
-	:
-else
-	echo "Invalid operation.";
-fi
-
-if ! test "$OP" = "noop"; then
 	# done doing whatever you want
 	echo "Done running.";
 
 	# exit
 	exit 0;
+
 fi
 
 # EOF
